#!/bin/bash
tracing=/sys/kernel/debug/tracing
flock=/var/tmp/.ftrace-lock
opt_force=0; opt_quiet=0

function usage {
	cat <<-END >&2
	USAGE: reset-ftrace [-fhq]
	                 -f              # force: delete ftrace lock file
	                 -q              # quiet: reset, but say nothing
	                 -h              # this usage message
	  eg,
	       reset-ftrace              # disable active ftrace session
END
	exit
}

function warn {
	if ! eval "$@"; then
		echo >&2 "WARNING: command failed \"$@\""
	fi
}

function die {
	echo >&2 "$@"
	exit 1
}

function vecho {
	(( opt_quiet )) && return
	echo "$@"
}

# write to file
function writefile {
	file=$1
	string=$2	# optional
	if [[ ! -w $file ]]; then
		echo >&2 "WARNING: file $file not writable/exists. Skipping."
		return
	fi
	vecho "$file, before:"
	(( ! opt_quiet )) && cat -n $file
	warn "echo $string > $file"
	vecho "$file, after:"
	(( ! opt_quiet )) && cat -n $file
	vecho
}

### process options
while getopts fhq opt
do
	case $opt in
	f)	opt_force=1 ;;
	q)	opt_quiet=1 ;;
	h|?)	usage ;;
	esac
done
shift $(( $OPTIND - 1 ))

### ftrace lock
if [[ -e $flock ]]; then
	if (( opt_force )); then
		warn rm $flock
	else
		echo -e >&2 "ERROR: ftrace lock ($flock) exists. It shows" \
		    "ftrace may be in use by PID $(cat $flock).\nDouble check" \
		    "to see if that PID is still active. If not, consider" \
		    "using -f to force a reset. Exiting."
		exit 1
	fi
fi

### reset ftrace state
vecho "Reseting ftrace state..."
vecho
cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?"
writefile current_tracer nop
writefile set_ftrace_filter
writefile set_graph_function
writefile set_ftrace_pid
writefile events/enable 0
writefile tracing_thresh 0
writefile kprobe_events
writefile tracing_on 1
vecho "Done."
